[Feature/delete bookmark] 북마크 불러오기 삭제 기능 구현
depromeet/imgoing-frontend pull request #126
Opened 2021-11-04 18:45 UTC by ykss

## 관련 이슈 연결
It will close #93 

## 변경/추가 사항, 자세한 설명
- 북마크 불러오기에서 북마크 아이템 삭제 기능 구현
- 삭제하면서 기존 태스크의 isBookmarked가 false 되게끔 구현하기 위해 bookmark 데이터에 taskId 추가하여 구현

## 그 외 그냥 하고 싶은 말
졸린정신에 해서 엉망일거 같은데, 수정은 계속계속하겠숩니다..!

## 최종 결과물 스크린샷

2021-11-05 13:10 UTC, eun-seong requested changes
새벽에 수고하셨습니다!!

어제 슬랙에서 논의했던 내용 중에, '북마크가 태스크로 중복으로 추가될 수 있냐'를 다시 논의해봐야 할 것 같습니다.
1. 중복 추가 가능
    1. 북마크를 추가하면 -> 태스크로 추가 (여러 개 가능)
    2. '불러오기' 버튼 클릭 시 이미 추가된 북마크를 구별하여 나타낼 필요 없음
    3. 북마크를 이미 불러왔을 경우에 해당 북마크를 삭제한다면
        * 해당 북마크가 태스크에 여러 개가 있다면 모두 북마크 해제 -> 태스크로 변경
        * 이 경우 task가 BookmarkId를 가지고 있는 함
2. 중복 추가 불가능
    1. 북마크를 추가하면 -> 태스크로 추가
    2. '불러오기' 버튼 클릭 시 이미 추가된 북마크는 불러오기에서 선택 체크가 되어 있어야 하나?
        * 되어 있다면, 선택 해제를 하면 이미 추가되었던 태스크에서 해당 북마크는 제거가 되나?
        * 안되어 있다면, 북마크 중복 추가 방지를 어떻게 할 것인가?
    3. 북마크를 이미 불러왔을 경우에 해당 북마크를 삭제한다면
        * 북마크 해제 -> 태스크로 변경
        * bookmark가 taskId를 가지고 있어도 상관없지만 약간 어색함


현재 PR에서는 중복 추가 불가능이라 생각했을 때 2-2 번이 문제가 있는 것 같습니다!
논의 후 수정이 다시 필요할 것 같습니다🥺

2021-11-05 13:32 UTC, ykss commented on imgoing-frontend/src/components/Modal/LoadBookmarkModal.tsx
> +            taskId={bookmark.taskId}
👍

2021-11-05 13:35 UTC, ykss commented on imgoing-frontend/src/modules/thunks/bookmark.ts
> +  taskId: newTask.id,
오 그러네요 ㅎㅎ ! 반영하겠습니다.

2021-11-05 13:35 UTC, ykss commented on imgoing-frontend/src/modules/thunks/bookmark.ts
> +      return ResToBookmark(data.data, newTask);
같이 반영하겠습니다!

2021-11-05 13:57 UTC, ykss commented on imgoing-frontend/src/modules/slices/stepOfAddingPlan.ts
> +      },
반영했습니다!

2021-11-05 13:59 UTC, ykss commented
말씀하신 부분들은 수정했고,
중복추가에 대한 부분은 같이 논의해봐야할것같아요..!

2021-11-05 14:03 UTC, eun-seong commented
어제 중복 추가 불가능하게 하자고 논의가 되었고 경상님도 아마 그렇게 생각하시고 코드를 짜셨을텐데,
위에서 말씀드린 2-2 부분이 현재 코드에서 문제가 되어서 말씀드린 겁니다!!

중복 추가가 불가능하다면,
이미 추가한 북마크에 대해서는 '불러오기' 모달이 떴을 때 중복 추가를 할 수 없게 하는 무언가가 추가되어야 할 것 같아서요.
예를 들면, 1) 이미 선택이 되었다고 나타내거나 2) 추가된 북마크는 불러오기 리스트에서 아예 보여주지 않거나
하는 방식을 말씀드린 겁니다.

현재는 아무런 장치가 없어서 중복 추가가 가능하고, 북마크가 taskId를 가지고 있기 때문에 새로 추가된 태스크로 Id가 업데이트될 것이고, 그럼 북마크를 삭제했을 경우에 이전에 추가했던 북마크는 남아 있고, 이후에 추가된 북마크만 태스크로 변경될 것 같습니다.
(참고로 지금 서버에서 task 삭제 오류가 있어서 실행되지 않습니다. 테스트 불가ㅠㅠ)

2021-11-06 00:20 UTC, eun-seong commented
북마크를 삭제할 때 `delete` task api를 사용하지 않고 해당 북마크의 `isBookmarked` 피쳐를 false로 수정하는 `put` api를 사용해야 할 것 같습니다!
그래야 해당 북마크를 사용하고 있던 일정에서도 북마크가 해제되는 방식으로 진행할 수 있을 것 같아요.

2021-11-12 13:15 UTC, closed without merging