설정 페이지 UI 구현
depromeet/imgoing-frontend pull request #190
Opened 2021-11-27 08:49 UTC by ykss

## 관련 이슈 연결
It will close #189 

## 변경/추가 사항, 자세한 설명
기본적인 설정 페이지 UI만 구현하였고, 데이터나 기능 등은 계속 업데이트하도록 해야될 것 같습니다.
확정된 디자인이 설정 페이지 밖에 없었어서, 그거부터 진행했습니다.

- 앱 실행하면 뷰가 일부분만 보이는 현상? 같은데 있어서 기본 `App.tsx` 고치니까 정상으로보여서 일단 건드렸는데, 이부분은 수정필요하면 말씀해주세요...!
- icons 패키지가 `packages.json`에 추가가 안되어있어서 추가했습니다.
- BottomTab 부분 이름만 일단 바꿨습니다. 아이콘이랑 변경하는 디테일등은 추후에 따로 이슈해서 작업해야될것같네요.
- MyPlanScreen 부분이 파일명이랑 컴포넌트 명이 달라서 수정했습니다!
- 일부 필요한 svg 아이콘 추가했습니다.
- 일부 import에서 cycle 오류가 떠서 그부분 import 경로 수정했습니다.
- 그외에는 컴포넌트 자잘한 수정 및 자잘한 컴포넌트 추가도 포함되었습니다.

## 그 외 전달 사항
또 의도치않게 PR이 커져버렸네요 ㅠㅠ 오랜만이라..

## 최종 결과물 스크린샷
![image](https://user-images.githubusercontent.com/35093128/143674699-b88e7747-6f5f-4e76-91e4-0a3034e6368f.png)

2021-11-28 06:40 UTC, eungyeole approved these changes
수고하셨습니다

2021-11-29 11:39 UTC, eun-seong requested changes
수고하셨씁니다👍
코멘트 단 것 중에는 제 주관적인 의견이 있는 것도 있으니까 아니다 싶으면 바로 말씀해주세용ㅎㅎ

그리고 한 가지 더 짚고 넘어갈 게 있는데,
컴포넌트에 height를 지정 크기로 사용하는 게 많은 것 같아요!

padding이나 margin값들은 피그마에 따라서 지정 크기를 사용하는 게 맞는 경우가 더 많겠지만,
텍스트가 들어가는 것들, 그리고 화면의 크기에 따라서 영향을 받을 수 있는 것들은 지정 크기를 사용하지 않고 flex나 %를 사용하는 게 더 좋을 것 같습니다!
코멘트에도 몇 가지 써놓긴 했는데, 이번 PR에 포함이 되지 않는 것들도 많이 보이더라구용

저번 기본 컴포넌트PR 때 제가 경황이 없어서 제대로 살펴보지 못하고, 이제와서 말씀드려서 죄송합니다ㅠㅠ
한 번 확인해보시고 코멘트 주세요🙏

2021-11-29 11:39 UTC, eun-seong commented on packages/app/App.tsx
> +import { StyleSheet, SafeAreaView } from 'react-native';
사용하지 않는 변수, 모듈은 제거해주세용~!

2021-11-29 11:39 UTC, eun-seong commented on packages/ui/src/components/ListContainer.tsx
>      width: 244,
불필요한 style은 삭제해도 될 것같습니다!

2021-11-29 11:39 UTC, eun-seong commented on packages/app/src/components/Profile.tsx
> +    height: '20%',
height를 주는 것보다, padding값으로 높이를 조절하는 게 좋을 것 같아요~
`paddingVertical`값을 줘서, 화면이 커지더라도 일정한 크기를 유지할 수 있게요!

2021-11-29 11:39 UTC, eun-seong commented on packages/app/src/components/Profile.tsx
> +  avatar: { flex: 1, paddingHorizontal: 16 },
이미지가 들어갈 경우에 사이즈를 꼭 지정을 해줘야 해서,
Svg의 width에 따르지 않고 View에서 width를 지정사이즈로 해주는 게 좋을 것같습니당
피그마에서는 72픽셀이네요!

2021-11-29 11:39 UTC, eun-seong commented on packages/app/src/components/Profile.tsx
> +        <SvgXml xml={profile_default_img} width='100%' fill={colors.blue} />
디폴트 자체를 svg로 가져오기보다 background를 깔고 로고를 크기 조절을 해서 넣는 건 어떨까요?
그러면 이미지가 들어왔을 때도 관리하기 더 쉬울 것같습니당ㅎㅎ

2021-11-29 11:39 UTC, eun-seong commented on packages/ui/src/components/Stack.tsx
>      height: 32,
타이틀에 height를 지정하지 않고 wrapper에 paddingVertical 값을 지정해주는 게 더 좋을 것같아요!
디바이스마다 폰트 크기가 다를 수 있는데(디바이스 설정에 따라서) 그 값이 클 경우에 글자가 잘려보일 수도 있을 것 같습니당

2021-11-29 11:39 UTC, eun-seong commented on packages/ui/src/components/ListContainer.tsx
>      <Pressable style={[styles.wrapper, { paddingVertical: wrapperPadding }]} onPress={onClick}>
혹시 wrapper 속성에 width를 95% 주신 이유가 따로 있을까요??
이 컴포넌트의 경우에는 다른 곳에서 가져다 쓰는 컨테이너의 역할이 더 커서, 혹시 padding값을 조절할 경우에는 사용하는 곳에서 집어넣는게 더 맞는 것 같습니다!
그리고 디바이스의 width가 넓어질 경우 컴포넌트 안의 width가 불안정하다고 느껴질 것 같아용

2021-11-29 11:39 UTC, eun-seong commented on packages/app/src/screens/SettingsScreen.tsx
> +      <Profile />
```suggestion
    <View style={styles.wrapper}>
      <ScrollView>
        <Profile />
```

TabNavigation을 사용하고 header가 있는 경우에는 굳이 SafeAreaView를 사용하지 않아도 될 것같아요!
그리고 설정 화면의 경우 경험상 리스트가 꽉 차지 않아도 스크롤이 가능한 경우가 더 많은 것같아서, ScrollView를 넣는 건 어떤가요?ㅎㅎ

2021-11-29 14:43 UTC, ykss commented on packages/ui/src/components/ListContainer.tsx
>      <Pressable style={[styles.wrapper, { paddingVertical: wrapperPadding }]} onPress={onClick}>
그렇네요..! 이부분 수정했습니다.

2021-11-29 14:44 UTC, ykss commented on packages/ui/src/components/ListContainer.tsx
>      width: 244,
불필요한 부분 flex를 말씀하신건가요? children이랑 너비 비율 맞추려고 사용한 부분입니다..!

2021-11-29 14:47 UTC, ykss commented on packages/ui/src/components/Stack.tsx
>      height: 32,
그렇네요! 수정했습니다

2021-11-29 14:48 UTC, ykss commented on packages/app/src/components/Profile.tsx
> +    height: '20%',
그렇군요..! 높이조절은 패딩으로..!

2021-11-29 14:56 UTC, ykss commented on packages/app/src/screens/SettingsScreen.tsx
> +      <Profile />
ScrollView로 하는게 맞는 것 같아요!! ㅎㅎ 그리고 header 있는 경우에도 다 SafeAreaView로 일단 해놨었는데, 일단 피그마 화면 토대로 바꿔놨습니다!

2021-11-29 15:12 UTC, ykss commented
말씀해주신 부분 반영해서 올렸습니다! 
바쁘실텐데 자세하게 리뷰해주셔서 감사합니다..!!

2021-11-29 22:15 UTC, eun-seong commented on packages/ui/src/components/ListContainer.tsx
>      width: 244,
width를 말씀드린겁니당 ㅎㅎㅎ
flex가 있어서 고정된 width값이 필요없을 것같아요!

2021-11-29 22:17 UTC, eun-seong approved these changes
수고하셨습니다😊

2021-11-30 11:09 UTC, ykss commented on packages/ui/src/components/ListContainer.tsx
>      width: 244,
아아 수정했습니다 !! ㅎㅎ

2021-11-30 11:09 UTC, merged