홈 화면 마크업
depromeet/imgoing-frontend pull request #196
Opened 2021-12-15 12:27 UTC by eun-seong

## 관련 이슈 연결
* it closes #194 

## 변경/추가 사항, 자세한 설명
* 홈 화면 마크업 완료했습니다.
* 컴포넌트를 잘게 쪼개서 파일이 많아보일 수 있는데, 그게 맞습니다. 하하     
   구조 설계하느라고 머리가 조금 아팠습니다...
* 애니메이션을 추가했어요!      
   ```js
   LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
   ```
   라는 걸 사용하니까 커스텀할 필요도 없이 너무 편하게 되더라구요!

## 그 외 전달 사항

## 최종 결과물 스크린샷

#### 일정 진행 중

<img src="https://user-images.githubusercontent.com/49540564/146186198-66d8b462-37d3-448c-b736-01d8c7b4cdaf.png" width=300/>

#### 가이드

<img src="https://user-images.githubusercontent.com/49540564/146186313-23666b8e-e471-44b3-9308-482e0ef8641a.png" width=300/>

#### 애니메이션

<img src="https://user-images.githubusercontent.com/49540564/146186416-95495158-083c-4261-8df0-3108e06a6b3a.gif" width=300/>

2021-12-15 13:00 UTC, ykss commented on packages/app/App.tsx
> +    UIManager.setLayoutAnimationEnabledExperimental(true);
`UIManager` 사용하면 어떤 부분 역할을 해주는건가요?

2021-12-15 13:08 UTC, ykss commented on packages/app/src/screens/HomeScreen.tsx
> +    <SafeAreaView style={styles.container}>
![image](https://user-images.githubusercontent.com/35093128/146191970-fa3bf8cf-dd4f-49b3-9bee-9b46c389f584.png)
안드폰에서 테스트했을때 스테이터스바랑 알림,도움말 페이지 아이콘이랑 같은 높이에 있는데 
아이폰에뮬에서는 정상적이네요!

2021-12-15 13:08 UTC, ykss commented on packages/app/src/screens/HomeScreen.tsx
> +    <SafeAreaView style={styles.container}>
폰에서는 카메라 노치때문에 안보여요!

2021-12-15 13:09 UTC, ykss commented on packages/ui/src/components/SvgIcon.tsx
> +import React from 'react';
이 컴포넌트는 버튼도 svg를 버튼으로도 사용하기 위해서 만든게 맞나요?

2021-12-15 13:11 UTC, ykss commented on packages/icons/src/index.ts
> +export const icon_arrowUp = `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
이거 뭔가 제가 썼던 아이콘이랑 같을거같은데, 다른 이름으로 추가되었을거같네요! 추후에 정리하면될것같습니다.

2021-12-15 13:30 UTC, ykss commented on packages/app/src/components/Home/TopContents/Task.tsx
> +      <View style={[styles.flexRow, styles.time]}>
아 이런식으로 스타일을 여러개 적용하는 방식 좋네요..! 중복도 줄일 수 있고... 👍

2021-12-15 14:13 UTC, ykss commented on packages/app/src/components/Home/Schedule/Plan.tsx
> +  const [expanded, toggleExpanded] = useState(false);
타입추가해도 좋을거같아용

2021-12-15 14:24 UTC, ykss commented on packages/app/src/components/Home/Schedule/Plan.tsx
> +              LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
아까 UIManager가 여기랑 연관되는건가 보군요..! 이거 약속페이지에도 동일하게 적용해도 좋을것같네요..! 좋습니다~

2021-12-15 14:28 UTC, ykss approved these changes
너무 수고하셨습니다!! 금방금방 잘해주셨네요..ㅎㅎ!!

2021-12-15 14:31 UTC, eun-seong commented on packages/ui/src/components/SvgIcon.tsx
> +import React from 'react';
엇 맞습니다! 제가 적어놓는다는 걸 깜빡했네요 ㅎㅎ
PR에 추가했습니다!

2021-12-15 14:32 UTC, eun-seong commented on packages/icons/src/index.ts
> +export const icon_arrowUp = `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
아 추가를 하셨군요! 나중에 머지되는 PR에서 수정하면 될 것같네요 ㅎㅎ

2021-12-15 14:34 UTC, eun-seong commented on packages/app/src/components/Home/Schedule/Plan.tsx
> +  const [expanded, toggleExpanded] = useState(false);
typescript가 알아서 타입 추론을 해줘서 생략했습니다!
저희 스터디한 이펙티브 타입스크립트에서 불필요한 타입 선언은 지양하는 게 좋다고 해서,
타입 추론이 명확히 되는 곳은 타입 기재를 안하려고 하고 있습니다 ㅎㅎ

2021-12-15 14:35 UTC, eun-seong commented on packages/app/App.tsx
> +    UIManager.setLayoutAnimationEnabledExperimental(true);
`LayoutAnimation`을 사용하려면 안드로이드 버전에서 이 코드를 꼭 실행해줘야 한다고 하더라구요~

https://reactnative.dev/docs/layoutanimation

2021-12-15 14:38 UTC, eun-seong commented on packages/app/src/screens/HomeScreen.tsx
> +    <SafeAreaView style={styles.container}>
`SafeAreaView` 사용했는데, 이상하네요...
원인을 찾아보겠습니다

2021-12-15 14:42 UTC, eun-seong commented on packages/app/src/screens/HomeScreen.tsx
> +    <SafeAreaView style={styles.container}>
`react-native`의 모듈이 아닌 `react-native-safe-area-context` 모듈을 사용해야 하네요!
수정했습니다🙌

2021-12-15 14:42 UTC, eun-seong commented on packages/app/src/screens/HomeScreen.tsx
> +    <SafeAreaView style={styles.container}>
안드로이드 잊고 있었는데 확인해주셔서 감사합니다 ㅎㅎ

2021-12-17 13:18 UTC, eungyeole requested changes

2021-12-17 13:18 UTC, eungyeole commented on packages/ui/src/components/TextBadge.tsx
> +  const { text, backgroundColor = 'grayMedium', textColor = colors.blue } = props;
이 부분때문에 고민이 많은데 ColorNames 타입으로 가져가는 것 보다 string으로 가져가는것이 더 좋을까요?
Text나 Button쓰면서 colors를 계속 import할 필요가 있을까 싶기도 하구...

일단 이부분을 이렇게 수정할려면 TextBadgeProps의 textColor 타입도 string으로 바꿔줘야할것 같습니다.

2021-12-17 13:25 UTC, eun-seong commented on packages/ui/src/components/TextBadge.tsx
> +  const { text, backgroundColor = 'grayMedium', textColor = colors.blue } = props;
제가 왜 전에 수정을 했는지 모르겠지만 머지하면서 다시 되돌려졌습니다..!
저도 `ColorNames`로 사용하는 게 더 좋습니다 ㅎㅎ

2021-12-17 13:50 UTC, eungyeole approved these changes
애니메이션까지... 수고 하셨습니다!

2021-12-17 14:02 UTC, merged