설정 서브 페이지 마크업 및 프로필 이미지 크기 수정
depromeet/imgoing-frontend pull request #200
Opened 2021-12-16 16:53 UTC by ykss

## 관련 이슈 연결
It will close #191 설정 서브 페이지 마크업
It will close #198 프로필 사진 이미지 크기 수정

## 변경/추가 사항, 자세한 설명
- 설정페이지에서 연결되는 서브 페이지 마크업
- 프로필 이미지 크기 문제 수정 
  - 제꺼에서는 제대로 보이는데 아직도 문제있는지 확인부탁드려용

## 최종 결과물 스크린샷
![image](https://user-images.githubusercontent.com/35093128/146413380-2ccb8ce5-05f0-4f92-9d61-be63daa1b792.png)
![image](https://user-images.githubusercontent.com/35093128/146414043-fcec5af3-a8ff-4ab9-8eaf-b7110a7e80f9.png)

안드로이드 갤10 5G
![image](https://user-images.githubusercontent.com/35093128/146413561-495b033f-9cbf-4b04-849a-672cca7393c0.png)

2021-12-17 12:50 UTC, eungyeole requested changes

2021-12-17 12:50 UTC, eungyeole commented on packages/ui/src/components/Button.tsx
> -  const backgroundColor = disabled ? colors.grayMedium : colors.blue;
여기서 이걸 지워버리면 disabled 상태일때 색이 변경되지 않을것같네요

2021-12-17 12:50 UTC, eungyeole commented on packages/ui/src/components/Stack.tsx
> +  children: React.ReactNode[] | React.ReactNode;
React.ReactNode[]이 굳이 필요 없을것 같습니다.

2021-12-17 12:57 UTC, ykss commented on packages/ui/src/components/Button.tsx
> -  const backgroundColor = disabled ? colors.grayMedium : colors.blue;
흠 이게 스타일만 disabled이고 클릭은 할수 있는 디자인의 버튼들이있어서 배경색을 따로 지정해주는걸로 했었습니다..!

2021-12-17 13:06 UTC, eun-seong commented on packages/ui/src/components/Button.tsx
> -  const backgroundColor = disabled ? colors.grayMedium : colors.blue;
혹시 어떤 버튼인가요?

2021-12-17 13:08 UTC, ykss commented on packages/ui/src/components/Button.tsx
> -  const backgroundColor = disabled ? colors.grayMedium : colors.blue;
![image](https://user-images.githubusercontent.com/35093128/146549310-d9f9a20c-f620-4b6b-a433-1490e7d20944.png)
이 버튼인데 이게 클릭불가능하면 안되는 버튼 같아서요!

2021-12-17 13:09 UTC, ykss commented on packages/ui/src/components/Button.tsx
> -  const backgroundColor = disabled ? colors.grayMedium : colors.blue;
지금보니 이부분만 다른거같기도하네요..!

2021-12-17 13:31 UTC, eun-seong commented on packages/ui/src/components/Button.tsx
> -  const backgroundColor = disabled ? colors.grayMedium : colors.blue;
@eungyeole 이 부분 고려해서 `disabled`와 `background`를 따로 가져가게끔하면 될 것같네요!

2021-12-17 13:53 UTC, eungyeole approved these changes
수고하셨습니다!

2021-12-17 14:01 UTC, eun-seong requested changes
수고하셨습니다☺️

아, 그리고 사진 붙이실 때 바로 붙이면 width가 100%가 되어버려서 가독성이 너무 안좋아지네요ㅠㅠ
```
<img src="hihi" width=300/>
```
이렇게 태그로 해서 width 조정해주시면 보기 더 편할 것 같습니다 ㅎㅎ

2021-12-17 14:01 UTC, eun-seong commented on packages/app/src/components/Profile.tsx
> +    borderRadius: 36,
flex 비율로 나누게 돼서 프로필 이미지 비율이 타원으로 깨지는 것 같습니다😄
지금 1:4 비율인데, 1에 해당하는 width가 72px보다 작아지게 되면 발생하는 현상같아요 ㅎㅎ

```ts
const styles = StyleSheet.create({
  wrapper: {
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  avatar: {
    width: 72,
    height: 72,
    marginRight: 16,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.blueLight,
  },
});
```

여기 styleSheet 자체를 이렇게 변경하면 어떨까용?

2021-12-17 14:01 UTC, eun-seong commented on packages/app/src/navigation/RootNavigation.tsx
> +          },
```suggestion
          headerLeft: () => <SvgXml
                xml={icon_back}
                style={{ marginLeft: 16 }}
                fill={colors.black}
                onPressOut={() => navigation.goBack()}
              />
```

depth가 너무 깊어지는 것 같아서, 의미없는 부분은 제거하는 게 어떨까용?

2021-12-17 14:01 UTC, eun-seong commented on packages/app/src/navigation/RootNavigation.tsx
> +          },
위의 부분과 같은 의견입니다~!

2021-12-17 14:01 UTC, eun-seong commented on packages/app/src/screens/AccountManageScreen.tsx
> +});
```suggestion
const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    display: 'flex',
    backgroundColor: colors.white,
    justifyContent: 'space-between',
  },
  buttonBox: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingBottom: getBottomSpace(),
  },
  button: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gap: {
    width: 8,
  },
});
```

이렇게 변경하는 게 어떨까요?
`View`의 경우에는 width 디폴트가 100%라서 해줄 필요 없고, 이건 스크린컴포넌트니까 height를 100%하는 것보다 flex를 사용하는 게 더 좋아보입니다 ㅎㅎ
위에 `Stack`으로 감싸져 있으니 버튼을 내리려고 `space-between` 사용했구요~!
변수 이름은,, 카멜케이스로 통일부탁드려용

`getBottomSpace()`는 [이 패키지](https://github.com/ptelad/react-native-iphone-x-helper#readme)에 있는 함수인데 제가 이 후 PR에서 ui 모듈에 추가해놓은 상태입니다.
ui보다는 app에 있는 게 더 좋을 것 같아서, 경상님이 이거 추가하시고 제가 이후 PR에서 `peerDependencies`로 변경하겠습니다.

app에서 
```
yarn add react-native-iphone-x-helper
```
해주시면 될 것 같아요~


추가로, 아래 `PolicyScreen`에도 여기 코멘트에 적용되는 게 있는 것 같으니 확인부탁드립니다.

2021-12-17 14:01 UTC, eun-seong commented on packages/app/src/screens/PolicyScreen.tsx
> +
```suggestion
  main_text: { 
    marginBottom: 16 
  },
```

스타일 수정 부탁드려용

2021-12-17 16:39 UTC, ykss commented on packages/app/src/screens/AccountManageScreen.tsx
> +});
자세한 리뷰 감사합니다! 많이배우네요! 

근데 혹시 `getBottomSpace()` 이거는 아이폰쪽 관련 패키지인것같은데, 혹시 해당패키지로 적용해도 안드로이드에 문제없는게 정상일까요?
제껄로 테스트했을때는 안드로이드폰에서는 버튼 아래쪽이 좀 잘리는 것 같더라구요.

2021-12-17 16:44 UTC, ykss commented on packages/app/src/components/Profile.tsx
> +    borderRadius: 36,
아 그거 때문이었군요...!! 최곱니다..!

2021-12-17 17:01 UTC, ykss commented
정말 세세한 리뷰 감사합니다! 일단 수정사항 1차적으로 반영하였고, 
`getBottomSpace()` 대한 부분만 해결되면 될것같은데, 일단은 명시적으로 패딩값으로 주니까
아이폰 안드로이드 다 괜찮은 것 같아서 그렇게 적용해놨습니다!

2021-12-18 01:35 UTC, eun-seong commented on packages/app/src/screens/AccountManageScreen.tsx
> +});
엇 공식 리드미에는 iphoneX 이상일 경우에만 적용이되고 나머지는 0으로 적용된다고 기재되어 있었는데, 아닌가요? 제가 이제까지 했을 때는 이상이 없어는데..! 다시 확인해보겠습니다 :)

https://github.com/ptelad/react-native-iphone-x-helper#getbottomspace

2021-12-18 01:47 UTC, eun-seong commented on packages/app/src/screens/AccountManageScreen.tsx
> +});
앗 당연한거네요 ㅋㅋㅋ
`getBottomSpace()`는 아이폰 노치가 있는 경우에 하단 바가 있어서 그 공간 만큼만 띄워주는 거라
```ts
    paddingBottom: Platform.OS === 'android' ? 20 : getBottomSpace(),
```

이렇게 작성하면 될 것 같습니다!

<img src="https://user-images.githubusercontent.com/49540564/146625005-ec3953dd-e715-4706-9261-f9ccd4b5625b.png" width=400/>

2021-12-18 13:40 UTC, ykss commented on packages/app/src/screens/AccountManageScreen.tsx
> +});
좋습니다~~

2021-12-18 13:41 UTC, ykss commented
> 수고하셨습니다☺️
> 
> 아, 그리고 사진 붙이실 때 바로 붙이면 width가 100%가 되어버려서 가독성이 너무 안좋아지네요ㅠㅠ
> 
> ```
> <img src="hihi" width=300/>
> ```
> 
> 이렇게 태그로 해서 width 조정해주시면 보기 더 편할 것 같습니다 ㅎㅎ

혹시 이건 어떤 부분 말씀하신건가요..!?

2021-12-18 13:47 UTC, eun-seong commented
앗 PR이나 코멘트달 때 말한거였어요!
지금 있는 pr에는 제가 수정해놨습니다..!

! [image](url)
이 형태로 쓰면 사진이 너무 커져버려서요ㅠㅠ

2021-12-18 13:57 UTC, ykss commented
> 앗 PR이나 코멘트에 이미지 첨부할 때 말한거였어요! 지금 있는 pr에는 제가 수정해놨습니다..!
> 
> ! [image] (url) 이 형태로 쓰면 사진이 너무 커져버려서요ㅠㅠ @eungyeole 은결님도 img 태그로 부탁드려용

아 복붙으로 했엇어서 신경을 못썼었네요~~ 앞으로 크기 조절 하겠습니다! ㅎㅎ 
이 PR은 이제 머지해도될까요?

2021-12-18 14:07 UTC, eun-seong commented
네! 머지해도 될 것 같습니다☺️

2021-12-18 14:15 UTC, merged