Feat/routine modal
depromeet/imgoing-frontend pull request #218
Opened 2022-02-05 15:09 UTC by ykss

## 관련 이슈 연결
It will close #211

## 변경/추가 사항, 자세한 설명
- 루틴관련 모달 마크업 적용하였습니다.
- 탭 아이콘은 예전에 제가 적용하려고했던거 같은데, 합칠때 이부분 컴플릭트나면 은성님이 해주신걸로 적용하면 될것같습니다.

## 그 외 전달 사항
- 오랜만에 이어서 하려니까, 맥을 다시 잡아야할 것 같습니다. 일단 하던 브랜치까지 마무리해서 올리고, 다시 맥잡고 달려보겠습니다. 오랜시간 제대로 못해서 죄송하네요 ㅠㅠ

## 최종 결과물 스크린샷
x

2022-02-06 10:43 UTC, eun-seong requested changes
수고하셨습니다😄
쉬는 시간이 길어지면 직접 작성한 코드도 다시 봐야 해서 시간이 배로 걸리죠ㅠㅠ 

코멘트에도 남긴 건데, 탭바 아이콘 부분은 충돌이 났기도 하고 현재 develope 브랜치의 코드가 아이콘을 색깔별로 나눌 필요 없이 `fill`을 변경하는 방식이라서,
코드가 약간 달라서 삭제해주시는 게 좋을 것 같습니다☺️

2022-02-06 10:43 UTC, eun-seong commented on package.json
> +  "dependencies": {
이거 workspace app 으로 옮겨주세요~

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/navigation/MainNavigation.tsx
> +        options={{
여기랑 `icons`의 탭바 아이콘들은 PR에 적어주신대로 삭제해야 할 것 같아요!
이미 적용이 되어 있는데 코드가 좀 달라서 삭제해주시는 게 좋을 듯 하네요 🙌

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/components/MyPlan/Routine/AddTaskModal.tsx
> +const AddTaskModal = ({}: AddTaskModalProps) => {
컴포넌트 네이밍은 동사로 시작하는 것보다 명사로 시작하는 게 좋을 것 같아요!
`AddingTaskModal` 정도루요..?

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/components/MyPlan/Routine/AddTaskModal.tsx
> +}
안쓰는 것들은 삭제해주세요..!

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/components/MyPlan/Routine/AddTaskModal.tsx
> +  type StepType = 'name' | 'duration';
타입이나 인터페이스는 컴포넌트 안보다 `types/index` 혹은 해당 컴포넌트 디렉토리 안에 따로 `type.ts`를 만들어서 두는 게 좋을 것 같습니다 😁

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/screens/RoutineEditScreen.tsx
> +          <TaskItem duration={task.time} title={task.name} type={'edit'} />
```suggestion
          <TaskItem key={task.id} duration={task.time} title={task.name} type={'edit'} />
```

`key`값 넣어주는 거 잊지 마세용🤗

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/screens/RoutineEditScreen.tsx
> +  };
```suggestion
  const toggleHistoryModal = (visible: boolean) => {
    // ...visible에 따른 기타 작업
    setHistoryModalVisible(visible);
  };
```


`toggleHistoryModal()`과 `toggleAddTaskModal()`의 용도를 잘 모르겠어요😢
버튼이 눌렸을 땐 이 함수들을 사용하지만, `Modal` 컴포넌트의 `setModalVisible`에는 `setHistoryModalVisible`을 전달하고 있네요.

모달이 제거될 때 입력했던 정보를 초기화 한다거나 하는 등의 추가적인 작업이 있을 경우에는 `Modal` 컴포넌트의 `setModalVisible`의 파라미터 `visiable`를 통해서 해야 할 것 같아요.
그럼 버튼 컴포넌트의 `onPress`에는 `setHistoryModalVisible(true)`를 실행하고, 
`Modal`의 `setModalVisiable`에 `toggleHistoryModal(visiable)` 함수를 실행해야 하는 게 맞지 않을까용?

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/components/MyPlan/Routine/HistoryModal.tsx
> +          <TaskItem title='물 마시기' duration={5} type={'add'} key={i} />
아직 마크업이라 그렇지만,
`key`같은 경우에는 `index`로 설정하지 않도록 나중에 꼭 수정해주셔용 😊

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/components/MyPlan/Routine/HistoryModal.tsx
> +  const historyData: any[] = [{}, {}, {}, {}, {}, {}];
```suggestion
  const historyData: any[] = Array.from({ length: 6 });
```

빈 배열 생성할 때 이렇게 하면 편합니다..!

2022-02-06 10:43 UTC, eun-seong commented on packages/app/src/components/MyPlan/Routine/TaskItem.tsx
> +          <SvgXml xml={type === 'edit' ? icon_delete : icon_add} />
여기 `Pressable` 부분은 `SvgIcon`으로 변경해주시면 좋을 것 같아요!

2022-02-06 10:43 UTC, eun-seong commented
그리고 screen의 수가 많아지니 어디가 어디인지 헷갈리기 시작하네요ㅠㅠ
탭바 별로 디렉토리를 나누어서 해당 탭 스크린에서만 사용되는 화면을 나누는 게 어떨까요? 공통은 common으로 두고요!
@eungyeole @ykss

2022-02-07 14:52 UTC, ykss commented
> 그리고 screen의 수가 많아지니 어디가 어디인지 헷갈리기 시작하네요ㅠㅠ 탭바 별로 디렉토리를 나누어서 해당 탭 스크린에서만 사용되는 화면을 나누는 게 어떨까요? 공통은 common으로 두고요! @eungyeole @ykss

맞아요 저도 이부분 헷갈리더라구요 그렇게 나누는것도 좋을거같아요

2022-02-08 03:14 UTC, eungyeole commented
@ykss @eun-seong 탭바별로 나누는거 찬성입니다! 오랜만에 봐서 그런지 더 헷갈리네요.. ㅠ

2022-02-08 03:26 UTC, eungyeole requested changes
수고하셨습니다! 요즘 너무 바쁜 것같네요 ㅠㅠ 다시 한번 마음잡고 시작해 보는 중인데 감이 안잡히네요..

2022-02-08 03:26 UTC, eungyeole commented on packages/app/src/components/MyPlan/Routine/TaskItem.tsx
> +type itemType = 'default' | 'edit' | 'add';
Type명 PascalCase로 변경해야 할 것 같아요!

2022-02-08 03:26 UTC, eungyeole commented on packages/app/src/screens/RoutineEditScreen.tsx
> +              toggleHistoryModal();
이벤트가 하나만 있어서 화살표 함수로 감싸지 않아도 될 것같아요! (추가로 이벤트 넣을려고 하신거면 그대로 둬도 괜찮을것 같네요)

2022-02-08 03:26 UTC, eungyeole commented on packages/app/src/screens/RoutineEditScreen.tsx
> +            toggleAddTaskModal();
여기도!

2022-02-09 16:05 UTC, ykss commented on package.json
> +  "dependencies": {
아 그렇네요!! 확인했습니다!

2022-02-09 16:08 UTC, ykss commented on packages/app/src/navigation/MainNavigation.tsx
> +        options={{
넵!

2022-02-09 16:34 UTC, ykss commented on packages/app/src/components/MyPlan/Routine/HistoryModal.tsx
> +  const historyData: any[] = [{}, {}, {}, {}, {}, {}];
꿀팁 감사합니닷!

2022-02-09 16:42 UTC, ykss commented on packages/app/src/screens/RoutineEditScreen.tsx
> +  };
왜때문에 이렇게 했었는지 모르겠네요 ㅠㅠ !! 말씀하신 부분이 맞는것 같아요. 불필요하게 함수를 추가했네요!

2022-02-10 14:40 UTC, eun-seong approved these changes
네비게이션 쪽에 충돌이 있네요! 확인하시고 머지하시면 될 것 같아요~
수고하셨습니다🙌

2022-02-11 15:35 UTC, merged